on:
  push:
    branches:
      - 'main'

name: Build Docker Image and Deploy to DEV
jobs:
  test:
    uses: remotemobprogramming/timer/.github/workflows/test.yml@main
  dockerbuild:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'temurin'
          java-version: '17'
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build
        run: ./mvnw spring-boot:build-image
      - name: Docker Tag
        run: docker tag remotemobprogramming/mob-timer remotemobprogramming/mob-timer:${{ github.sha }}
      - name: Docker Push Latest
        run: docker push remotemobprogramming/mob-timer:latest
      - name: Docker Push Tag
        run: docker push remotemobprogramming/mob-timer:${{ github.sha }}
  deployment:
    needs: dockerbuild
    environment: development
    concurrency: development
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_AUTH_TOKEN}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_DEV }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}