on:
  push:
    branches:
      - 'main'

name: Build Docker Image and Deploy to DEV
jobs:
  test:
    uses: remotemobprogramming/timer/.github/workflows/test.yml@main
  dockerbuild:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Java JDK
        uses: actions/setup-java@v3.5.1
        with:
          distribution: 'temurin'
          java-version: '11'
      - name: Login to DockerHub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Docker Build
        run: ./mvnw spring-boot:build-image
      - name: Docker Tag
        run: docker tag remotemobprogramming/mob-timer remotemobprogramming/mob-timer:${{ github.sha }}
      - name: Docker Push Latest
        run: docker push remotemobprogramming/mob-timer:latest
      - name: Docker Push Tag
        run: docker push remotemobprogramming/mob-timer:${{ github.sha }}
  deployment:
    uses: remotemobprogramming/timer/.github/workflows/testname.yml@main
    with:
      domain: dev.timer.mob.sh
      tag: ${{ github.sha }}
    secrets:
      SSH_HOST: ${{ secrets.SSH_HOST_DEV }}
      SSH_USERNAME: ${{ secrets.SSH_USERNAME }}
      SSH_KEY: ${{ secrets.SSH_KEY }}
