on:
  workflow_call:
    inputs:
      - domain:
          required: true
          type: string
      - tag:
          required: true
          type: string
    secrets:
      - SSH_HOST:
          required: true
          type: string
      - SSH_USERNAME:
          required: true
          type: string
      - SSH_KEY:
          required: true
          type: string
jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: deploy
        uses: appleboy/ssh-action@v0.1.5
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop mobtimer
            docker rm mobtimer
            docker run -d -e VIRTUAL_HOST=${{ inputs.domain }} -e LETSENCRYPT_HOST=${{ inputs.domain }} -e LETSENCRYPT_EMAIL=team@mob.sh -e PORT=80 --expose 80 --network=proxy --pull always --name mobtimer remotemobprogramming/mob-timer:${{ inputs.tag }}