on:
  release:
    types: [published]
name: Release
jobs:
  test:
    uses: remotemobprogramming/timer/.github/workflows/test.yml@main
  deployment:
    needs: test
    environment: production
    concurrency: production
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: akhileshns/heroku-deploy@v3.12.13
        with:
          heroku_api_key: ${{secrets.HEROKU_AUTH_TOKEN}}
          heroku_app_name: ${{ secrets.HEROKU_APP_NAME_PROD }}
          heroku_email: ${{ secrets.HEROKU_EMAIL }}