on:
  schedule:
    - cron: '*/5 * * * *'
name: Smoketest on PROD
jobs:
  smoketest:
    runs-on: ubuntu-latest
    name: Smoketest on PROD
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cypress run
        uses: cypress-io/github-action@v4
        with:
          working-directory: cypress
      - name: Upload screenshots
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/cypress/screenshots
      - name: Upload videos
        uses: actions/upload-artifact@v2
        if: failure()
        with:
          name: cypress-videos
          path: cypress/cypress/videos